### PR TITLE
Implement exercise leap

### PR DESCRIPTION
**Pull request by And-0**

### CODE REVIEW

**Comment by kytrinyx** [comment]
@And-0 Thanks so much for working on this! 🌷 

I'm sorry nobody saw it before now—that is unacceptable. I'm working on making better systems so contributions don't fall between the cracks.

As it is, this exercise does not follow the format of the existing ones (hello world, and bob).

screen shot 2017-06-11 at 12 33 00 am

There are a few things that need to be updated:

1. The README.md needs to be deleted. This file gets generated based on a number of files, as described in https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/exercise-readmes.md
1. The directory of the exercise needs to be moved into the `exercises` directory
1. The Makefile for this exercise is missing.

The full documentation about how to port an exercise is here: https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/porting-an-exercise.md

**Comment by NobbZ** [comment]
As initiator and former "maintainer" of this track I think I should chime in here.

The `Makefile` was initially for my convenience only. The haxe community seems to be mostly windows driven and seems to prefer to use a tool called `haxelib` for anything directly (which is simply wrapped by my makefile), also one simply can't assume that GNU-Make will be available for everyone. Its simply not common enough.

Therefore I think we should not force to add a maybe useless `Makefile` here, but discuss if it is really necessary.

----

Also I think that `leap` should be served before `bob`.

**Comment by kytrinyx** [comment]
@NobbZ OK. Since I am unfamiliar with the track I was aiming for consistency. I've updated my comment above.

**Comment by And-0** [comment]
@kytrinyx  Well it took a while, but I've updated the exercise to follow the format of the others! I'm getting an error message ("The Travis CI build failed") but I'm not quite sure what to do about that...? Sorry, I haven't touched this repo (and Github in general) in a long while so I' m a bit rusty.

**Comment by NobbZ** [comment]
The error message tells you about `leap` not having an UUID. You need to generate one that is unique to this exercise across all tracks. The current most `configlet` should have an option for that if I recall correctly, but you can use any UUID generator from the web. Its very unlikely to have a clash across the tracks.

Also as far as I can tell from the dii, you seem to have produced an invalid JSON. It looks quite like you had a margeconflict, and you just committed the simple diffed file:

```json
      "slug": "bob",
<<<<<<< HEAD
      "topics": []
    },
	{
      "difficulty": 1,
      "slug": "leap",
      "topics": []
=======
      "core": false,
      "unlocked_by": null,
      "difficulty": 1,
      "topics": [
 
      ]
>>>>>>> upstream/master
    }
```

Because of this, I'm wondering that `configlet` was able to find the exercises entry at all…

**Comment by And-0** [comment]
Thank you very much @NobbZ ! Stupid merge conflicts, that's what happens when you don't have your merge tool set up yet...

Thanks for the help, I've fixed the JSON and generated a UUID using `configlet` now.

**Comment by kytrinyx** [comment]
Thank you @And-0 🌻 I've merged this locally in 1c402521f9d9c7167fd20a9e1e8659b03e3d0c20 and pushed it up to master.

**Pull request closed without merging**
