### PR TITLE
Add space-age exercise

### PR DESCRIPTION
**Pull request by mfoda**

### CODE REVIEW

**Review by davidbruce — DISMISSED** [review]
I would like to see this exercise updated to be more inline with its [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/space-age/canonical-data.json) 

```haxe
package;

class SpaceAge {
    public static function age(seconds: Int, planet: String): Float{
        throw "Not Implemented"; // Delete this statement and write your own implementation.
    } 
}
```

**Comment by mfoda** [comment]
@davidbruce 
Ok. Do you think using an enum for planets is a good example here, or keep it string-based?

**Comment by davidbruce** [comment]
It would probably be easier to change your map's keys to strings.  Thanks again!

**Comment by mfoda** [comment]
Done! Should I also be fixing the `config.json` merge conflict? I'm a little unsure about what needs to be done there.

**Comment by davidbruce** [comment]
It's okay I've been taking care of the config.json conflicts.  It's just as I merge exercises Git cannot decide what order to place things unfortunately.  It would be annoying if I made people rebase/merge and fix a conflict everytime I pull in a new exercise PR.

**Review by BNAndras — APPROVED** [review]

**Review by BNAndras — APPROVED** [review]

**Pull request merged**
