### PR TITLE
Add haxe concepts placeholders

### PR DESCRIPTION
**Pull request by mfoda**
This is to initialize work on haxe concepts and make it a bit easier for others to pick one and contribute.
The concepts were copied from the C# track and adapted for haxe (reflecting names/terms used in the official docs), removing concepts not applying to haxe, and adding haxe-specific concepts.

Currently the list is not complete and a few like abstracts might be too advanced to cover. However it should be enough to get work and discussion started.

### CODE REVIEW

**Comment by mfoda** [comment]
@davidbruce please let me know if you see anything that you feel should/shouldn't be in this list.

**Comment by mfoda** [comment]
Whoops that last commit shouldn't have made it here.

**Comment by davidbruce** [comment]
I'm not sure how I feel about the concepts being so distinct.  I worry that students will find it tedious doing many short concepts vs larger ones that require more test cases. 

I've made a rough outline for a more condensed learning path.
If you agree with this approach we can flesh out the outline below.   Either way, thank you for your hardwork!

### Beginner 
Stuff you would generally find in C# and Java.

1. Getting Started and Hello World
2. Basic Types and Casting
3. Ifs, basic Switch, and Equality
4. Loops
5. Arrays and Vectors
6. Maps
7. Map and Array Comprehension
8. Basic Enums
9. Classes
10. Functions
11. Typedefs (Should probably warn about how these affect performance on statically typed targets)
12.  Interfaces
13.  Generics

### Intermediate
This is where the standard library gets and more niche Haxe specific features are introduced. 

1. Math and Operators
2. Date and Time
3. Templates
4. Regular Expressions
5. Option
5. Using statements
6. Lambda
7. Reflection 
8. Iterators
9. Function Bindings
10. EnumFlags (not really sure where to throw this, but its really useful)
11. Useful Annotations
12. Generalized Algebraic Data Types and Pattern matching
13. Abstract Types

### Advanced
Macros are undoubtedly the most difficult part of Haxe and I'm not sure how much we should cover them.  It might make sense to have a single concept that is pretty basic and then point users to the Haxe code cookbook.    

1. Macros

**Comment by mfoda** [comment]
@davidbruce This looks great and gives me a good structure to work from! I'll start with a few and will have more ideas/feedback once I start working on the concept exercises in tandem.

For the concepts being very distinct, I'm still catching up on the posts covering the problems that v3 is working on addressing and the reasoning behind designing things this way. From what I gather, concepts are meant to be bite-sized so that students are introduced to a single idea at a time, with a corresponding concept exercise that is meant to be solved using/focusing on that concept, hence the format. Once that's solved then other exercises become available (from v2) that combine other concepts as review and additional challenge.

That said, Haxe is a bit different in terms of the learning experience in that the majority of people new to it seem to be experienced developers coming in from other languages (according to the community survey if I remember correctly), who would probably prefer a more condensed learning path as you suggested, and I do think that's something we should keep in mind.

The main drawback I see in this approach is that we might need to come up with a different set of concept exercises instead of piggybacking on the great work being done in other tracks if we deviate from this format, which would be more work than simply copying/adapting (as I've been doing based off the C#/F# tracks xd).

Anyway, I'll work through a few concepts and exercises and see how other tracks are tackling this for ideas. Let's keep discussing and thanks for the feedback!

**Comment by mfoda** [comment]
Found [this](https://v3.exercism.io/exercises) which gives a nice overview of progress in other tracks and how concepts and concept exercises are being implemented.

**Comment by davidbruce** [comment]
I'll leave it up to you, if you'd prefer to stick with the way the C# course is doing things I think that's fair.   Perhaps that is the best route and in the future we can consolidate things based on user feedback.

**Pull request closed without merging**
