### PR TITLE
Add acronym exercise

### PR DESCRIPTION
**Pull request by mfoda**

### CODE REVIEW

**Comment by mfoda** [comment]
I had to unset `unlocked_by` in config.json to pass the checks, which I've been referencing from the C# config file. I assumed they would be the same across all tracks but maybe this is decided per track? 
Curious if that's also the case with `topics` and `difficulty` as I'm seeing different values in different tracks.

**Comment by NobbZ** [comment]
Yes, these are indeed per track.

As eg. a `two-fer` style exercise is pretty easy on python, where it can be implemented in a single line, though in something like C, it requires a good understanding of how "strings" and variadic arguments work, and therefore has different prerequisites to be understood.

Also, it doesn't make sense to have `topics` globally, as some languages might attach the "classes" topic or "custom operators" to the `list-ops` exercise, though both of these wouldn't make any sense in Erlang or Elixir, as both languages have neither "classes", nor the ability to define "custom operators".

**Comment by mfoda** [comment]
@NobbZ 
Ok, that makes sense. In that case I would need to put more thought into them rather than relying on the terminology and ordering of other tracks.
Thanks for the explanation.

**Review by davidbruce — APPROVED** [review]
LGTM

**Pull request merged**
