### PR TITLE
Add darts exercise

### PR DESCRIPTION
**Pull request by mfoda**

### CODE REVIEW

**Review by davidbruce — APPROVED** [review]
LGTM, rebased to v3

**Comment by davidbruce** [comment]
Whoops I goofed up something.  @ErikSchierboom would you mind approving this so I can squash and merge.

**Comment by iHiD** [comment]
This now has 155 changed files in it, so I don't think it's able to be squashed. I'll fix this later or tomorrow for you and merge it down :)

**Comment by davidbruce** [comment]
@iHiD I was able to fix it, sorry about that!

**Comment by iHiD** [comment]
Nice work! Thanks both of you! :)

**Pull request merged**
