### PR TITLE
Add gigasecond exercise

### PR DESCRIPTION
**Pull request by mfoda**
Note that I had to change the third test case's date value (1959-07-19) as the haxe Date class mentions that only dates in the range of 1970 through 2038 are supported consistently across platforms. The original date causes a `Result too large(mktime, )` failure.

### CODE REVIEW

**Comment by mfoda** [comment]
On a separate note, I noticed the default formatting in VS Code for haxe removes spaces between variable and type (as in `var number:Int`) and method signature as well. Should we stick to that to make it easier to maintain consistent formatting?

**Comment by NobbZ** [comment]
In my opinion consistent formatting is important, though it should not be defined by the editor, but an external formatter that could be run on CI as well.

Also in my opinion files really should have a trailing newline if they are code, some linux command line tools will have problems with them otherwise, as the POSIX standard actually requires a trailing new lines for text files according to the most common interpretation. Though I'd be fine without trailing newline as well, if it was consistent.

Though those rules should be defined in a contribution section of the `README.md` or a `CONTRIBUTING.md`, while also beeing enforced by CI.

This is not a review and does not request any changes on what is already in this PR, as I think it is more important to get the track running and defining processes when its thus far. This is more a general note about what I experienced as best practices.

**Comment by mfoda** [comment]
@NobbZ 
Yup that makes sense. From a quick search I see there's [haxe-formatter](https://github.com/HaxeCheckstyle/haxe-formatter) which is integrated and enabled by default in VS Code and can be compiled to run on CI I assume, and enforced with a `hxformat.json` file. I'm not very familiar with haxe though so there could be others.

Noted about the trailing new line. I'll see if there's any more feedback regarding formatting and do that in one pass once the exercises are merged. Thanks for the feedback

**Comment by BNAndras** [comment]
[https://community.haxe.org/t/date-class-without-time/911](https://community.haxe.org/t/date-class-without-time/911) indicates Haxe's standard `Date` object doesn't support daylight saving time so only the third test passes. I think we'll want to use the datetime library at https://lib.haxe.org/p/datetime/ so that'll need to be added to the test runner before we can update this exercise further and merge it in.

**Review by BNAndras — APPROVED** [review]

**Pull request merged**
